/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chubatova.gradle.multi.module.app;

import org.junit.jupiter.api.Test;
import java.lang.*;

import static org.junit.jupiter.api.Assertions.*;

class LinkedListTest {
    @Test void testConstructor() {
        assertEquals(0, 0);
    }

    @Test void testAdd() {
         assertEquals(0, 0);
    }

    @Test void testRemove() {
        assertEquals(0, 0);
    }

    @Test public void testRemoveMissing() {
         assertEquals(0, 0);
        assertEquals(2, list.size());
    }
}
