/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chubatova.gradle.multi.module.app;

import org.junit.jupiter.api.Test;
import java.lang.*;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MessageUtilsTest {
    @Test void testGetMessage() {
        try
        {
            //Thread.sleep(9);
            Thread.sleep(20000);
        }
        catch(InterruptedException e)
        {
            // this part is executed when an exception (in this example InterruptedException) occurs
        }

        assertEquals("Hello      World!", MessageUtils.getMessage());
    }
}
